#version: '3.9'
volumes:
  pg_database:
networks:
  rede_mentoria:
  rede_kafka:
services:

  my-postgres:
    image: postgres
    ports:
      - 5432:5432
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pg_database:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - ./scripts:/scripts
      - ./scripts/start.sh:/docker-entrypoint-initdb.d/start.sh
    networks:
      - rede_mentoria      
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: usergabs
      POSTGRES_DB: projeto_escola

  my-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15432:80
    environment:
       PGADMIN_DEFAULT_EMAIL: "gabrihell@hotmail.com"
       PGADMIN_DEFAULT_PASSWORD: "mysecretpassword"
    networks:
       - rede_mentoria 

  zookeeper:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - rede_kafka
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:   
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"